const words = {
    1: [
      { target: 'rápido', correct: 'veloz', incorrect: ['lento'] },
      { target: 'feliz', correct: 'contento', incorrect: ['triste'] },
      { target: 'grande', correct: 'enorme', incorrect: ['pequeño'] },
      { target: 'alto', correct: 'elevado', incorrect: ['bajo'] },
      { target: 'fácil', correct: 'sencillo', incorrect: ['difícil'] },
      { target: 'caliente', correct: 'ardiente', incorrect: ['frío'] },
      { target: 'nuevo', correct: 'reciente', incorrect: ['viejo'] },
      { target: 'fuerte', correct: 'robusto', incorrect: ['débil'] },
      { target: 'brillante', correct: 'resplandeciente', incorrect: ['opaco'] },
      { target: 'honesto', correct: 'íntegro', incorrect: ['mentiroso'] },
      { target: 'oscuro', correct: 'tenebroso', incorrect: ['luminoso'] },
      { target: 'frío', correct: 'helado', incorrect: ['caliente'] },
      { target: 'pequeño', correct: 'diminuto', incorrect: ['enorme'] },
      { target: 'ligero', correct: 'liviano', incorrect: ['pesado'] },
      { target: 'blando', correct: 'suave', incorrect: ['duro'] },
      { target: 'listo', correct: 'inteligente', incorrect: ['tonto'] },
      { target: 'limpio', correct: 'pulcro', incorrect: ['sucio'] },
      { target: 'triste', correct: 'afligido', incorrect: ['alegre'] },
      { target: 'débil', correct: 'frágil', incorrect: ['fuerte'] },
      { target: 'moderno', correct: 'actual', incorrect: ['antiguo'] },
    ],
    2: [
      { target: 'música', correct: 'melodía', incorrect: ['canción'] },
      { target: 'amistad', correct: 'compañerismo', incorrect: ['conocido'] },
      { target: 'inteligente', correct: 'listo', incorrect: ['estudioso'] },
      { target: 'oscuro', correct: 'sombrío', incorrect: ['nocturno'] },
      { target: 'sencillo', correct: 'simple', incorrect: ['elemental'] },
      { target: 'alegre', correct: 'jovial', incorrect: ['entusiasta'] },
      { target: 'fuerte', correct: 'robusto', incorrect: ['potente'] },
      { target: 'tranquilo', correct: 'calmo', incorrect: ['silencioso'] },
      { target: 'sabroso', correct: 'delicioso', incorrect: ['picante'] },
      { target: 'amable', correct: 'afable', incorrect: ['arrogante'] },
      { target: 'prisa', correct: 'apurado', incorrect: ['movimiento'] },
      { target: 'tormenta', correct: 'tempestad', incorrect: ['lluvia'] },
      { target: 'camino', correct: 'sendero', incorrect: ['carretera'] },
      { target: 'estrella', correct: 'astro', incorrect: ['constelación'] },
      { target: 'libro', correct: 'tomo', incorrect: ['página'] },
      { target: 'ciudad', correct: 'urbe', incorrect: ['pueblo'] },
      { target: 'fruta', correct: 'manzana', incorrect: ['vitamina'] },
      { target: 'verdura', correct: 'vegetal', incorrect: ['ensalada'] },
      { target: 'pintura', correct: 'óleo', incorrect: ['acrílico'] },
      { target: 'calle', correct: 'vía', incorrect: ['avenida'] },
    ],
    3: [
      { target: 'trabajo', correct: 'ocupación', incorrect: ['ocio', 'descanso'] },
      { target: 'honesto', correct: 'íntegro', incorrect: ['mentiroso', 'falso'] },
      { target: 'limpio', correct: 'aseado', incorrect: ['sucio', 'inmundo'] },
      { target: 'fácil', correct: 'sencillo', incorrect: ['difícil', 'complicado'] },
      { target: 'rápido', correct: 'veloz', incorrect: ['lento', 'pausado'] },
      { target: 'alegre', correct: 'jovial', incorrect: ['triste', 'melancólico'] },
      { target: 'fuerte', correct: 'robusto', incorrect: ['débil', 'frágil'] },
      { target: 'claro', correct: 'nítido', incorrect: ['oscuro', 'confuso'] },
      { target: 'amable', correct: 'afable', incorrect: ['grosero', 'rudo'] },
      { target: 'lógico', correct: 'razonable', incorrect: ['ilógico', 'absurdo'] },
      { target: 'pobre', correct: 'humilde', incorrect: ['rico', 'opulento'] },
      { target: 'nuevo', correct: 'actual', incorrect: ['antiguo', 'viejo'] },
      { target: 'despacio', correct: 'lento', incorrect: ['rápido', 'frenético'] },
      { target: 'vano', correct: 'superfluo', incorrect: ['útil', 'necesario'] },
      { target: 'sutil', correct: 'tenue', incorrect: ['notorio', 'evidente'] },
      { target: 'firme', correct: 'estable', incorrect: ['débil', 'vacilante'] },
      { target: 'pesado', correct: 'macizo', incorrect: ['ligero', 'liviano'] },
      { target: 'ocupado', correct: 'atareado', incorrect: ['libre', 'despreocupado'] },
      { target: 'pacífico', correct: 'tranquilo', incorrect: ['belicoso', 'violento'] },
      { target: 'ágil', correct: 'ligero', incorrect: ['torpe', 'lento'] },
    ],
    4: [
      { target: 'valiente', correct: 'intrépido', incorrect: ['decidido', 'apasionado'] },
      { target: 'curioso', correct: 'inquisitivo', incorrect: ['observador', 'explorador'] },
      { target: 'moderno', correct: 'contemporáneo', incorrect: ['actual', 'progresista'] },
      { target: 'elegante', correct: 'distinguido', incorrect: ['formal', 'clásico'] },
      { target: 'limpio', correct: 'aseado', incorrect: ['claro', 'luminoso'] },
      { target: 'brillante', correct: 'resplandeciente', incorrect: ['claro', 'vivo'] },
      { target: 'suave', correct: 'sedoso', incorrect: ['apacible', 'ligero'] },
      { target: 'fresco', correct: 'refrescante', incorrect: ['templado', 'agradable'] },
      { target: 'rico', correct: 'sabroso', incorrect: ['comestible', 'nutritivo'] },
      { target: 'ágil', correct: 'diestro', incorrect: ['rápido', 'liviano'] },
      { target: 'enérgico', correct: 'vigoroso', incorrect: ['activo', 'dinámico'] },
      { target: 'sofisticado', correct: 'refinado', incorrect: ['delicado', 'exquisito'] },
      { target: 'preciso', correct: 'exacto', incorrect: ['detallado', 'puntual'] },
      { target: 'coherente', correct: 'congruente', incorrect: ['lógico', 'ordenado'] },
      { target: 'generoso', correct: 'altruista', incorrect: ['solidario', 'desprendido'] },
      { target: 'armónico', correct: 'equilibrado', incorrect: ['compuesto', 'sereno'] },
      { target: 'efusivo', correct: 'entusiasta', incorrect: ['alegre', 'expresivo'] },
      { target: 'modesto', correct: 'humilde', incorrect: ['sencillo', 'tímido'] },
      { target: 'espontáneo', correct: 'natural', incorrect: ['sincero', 'casual'] },
      { target: 'sincero', correct: 'honesto', incorrect: ['franco', 'directo'] },
    ],
    5: [
      { target: 'sabio', correct: 'erudito', incorrect: ['ignorante', 'experto', 'necio'] },
      { target: 'ágil', correct: 'rápido', incorrect: ['lento', 'flexible', 'torpe'] },
      { target: 'firme', correct: 'resuelto', incorrect: ['inconstante', 'vacilante', 'dudoso'] },
      { target: 'elegante', correct: 'distinguido', incorrect: ['tosco', 'ordinario', 'grosero'] },
      { target: 'valioso', correct: 'preciado', incorrect: ['insignificante', 'común', 'barato'] },
      { target: 'audaz', correct: 'osado', incorrect: ['cauteloso', 'precavido', 'temeroso'] },
      { target: 'sutil', correct: 'tenue', incorrect: ['obvio', 'claro', 'manifiesto'] },
      { target: 'sereno', correct: 'calmo', incorrect: ['nervioso', 'agitado', 'inquieto'] },
      { target: 'rápido', correct: 'veloz', incorrect: ['lento', 'pausado', 'despacio'] },
      { target: 'fértil', correct: 'productivo', incorrect: ['estéril', 'árido', 'vacío'] },
      { target: 'pulcro', correct: 'limpio', incorrect: ['sucio', 'desprolijo', 'descuidado'] },
      { target: 'minucioso', correct: 'detallista', incorrect: ['descuidado', 'superficial', 'preciso'] },
      { target: 'cauto', correct: 'prudente', incorrect: ['imprudente', 'arriesgado', 'inconsciente'] },
      { target: 'efímero', correct: 'transitorio', incorrect: ['eterno', 'perpetuo', 'duradero'] },
      { target: 'prolífico', correct: 'productivo', incorrect: ['estéril', 'inútil', 'improductivo'] },
      { target: 'meticuloso', correct: 'escrupuloso', incorrect: ['descuidado', 'vago', 'impreciso'] },
      { target: 'perspicaz', correct: 'sagaz', incorrect: ['torpe', 'necio', 'lento'] },
      { target: 'versátil', correct: 'polifacético', incorrect: ['limitado', 'rígido', 'único'] },
      { target: 'vigoroso', correct: 'enérgico', incorrect: ['débil', 'flojo', 'lento'] },
      { target: 'constante', correct: 'perseverante', incorrect: ['variable', 'inconstante', 'irregular'] },
    ]
  };

  export default words;